#! /bin/sh
# Do common operations before a particular test.

case $# in
    0)   TAR_ARCHIVE_FORMATS=${TAR_ARCHIVE_FORMATS:-v7 oldgnu ustar posix gnu}
         for format in $TAR_ARCHIVE_FORMATS
         do
	     $0 $format
	     R=$?
	     test $R -eq 0 || exit $R
	 done
	 exit 0;;
    1)   if test "x$1" = xauto; then
            TAR_OPTIONS=
	 else    
            TAR_OPTIONS="--format=$1"
	 fi;;   
    *)   echo "Too many arguments" >&2 
         exit 2;;
esac    

mkdir tmp-$$
cd tmp-$$

out=
err=

export TAR_OPTIONS
#echo "$0 $1"
echo "$0 $1" > checking
exec 1> stdout
exec 2> stderr

	    
